---
abstract: 'a minimal, pure perl TOML parser and serializer'
author:
  - 'Jeff Ober <sysread@fastmail.fm>'
build_requires:
  Data::Dumper: '0'
  DateTime::Format::ISO8601: '0'
  DateTime::Format::RFC3339: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  TOML::Parser: '0'
  Test2::V0: '0'
  Test::More: '0'
  Test::Pod: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TOML-Tiny
recommends:
  Types::Serialiser: '0'
requires:
  Carp: '0'
  Data::Dumper: '0'
  Encode: '0'
  Exporter: '0'
  Math::BigInt: '1.999718'
  perl: '5.018'
resources:
  bugtracker: https://github.com/sysread/TOML-Tiny/issues
  homepage: https://github.com/sysread/TOML-Tiny
  repository: https://github.com/sysread/TOML-Tiny.git
version: '0.15'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
